---
name: rails
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      - "3306:3306"
    volumes:
      - ./tmp/services/mysql:/var/lib/mysql
  postgres:
    image: postgres:15.1-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/services/postgres:/var/lib/postgresql/data
  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
